title: MaClaw
email: support@maclaw.top
description: >-
  MaClaw: 三态智能体研发平台 - 程序员的AI编程伙伴
baseurl: ""
url: "https://rapidaicoder.github.io"
github_username: rapidai
github_repo: maclaw

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Custom settings
locales: ["en", "zh-cn"]
default_locale: "en"